on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [trunk]

name: Site

jobs:
  site:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install mdbook
        run: |
          curl -OL https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz
          mkdir bin
          tar xf mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz
          mv mdbook bin
          echo "$(pwd)/bin" >> "$GITHUB_PATH"

      - name: Run mdbook
        run: mdbook build
